### ISSUE TITLE
Support Digital Ocean provider

### ISSUE THREAD

**Issue by markuspoerschke** [andygrunwald/Jacobine-Vagrant#1]
For developers with a slow internet connection, it might be useful to offer a possibility to run the software on the internet. There is a way to use Vagrant hand in hand with Digital Ocean (a virtual private server provider).

Example and usage of the digital ocean provider:
https://github.com/smdahlen/vagrant-digitalocean

**Comment by andygrunwald** [comment]
This is still a good idea. But i won't continue Jacobine in the current way.
I am still interested in the whole topic, but won`t put to much effort in the current system.
I learned a lot and will focus on a different topics and when i come back to such a topic i will put this online in a new way.
This ticket will be closed to cleanup the project and to focus on new ideas for 2016 :tada:
